-- Создание таблицы
CREATE TABLE points (
    ID BIGINT NOT NULL,
    X NUMERIC(19,4) NOT NULL,
    Y NUMERIC(19,4) NOT NULL,
    R NUMERIC(19,4) NOT NULL,
    Hit CHAR(1) NOT NULL,
    Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);
